3450 #!/usr/bin/perl -w
3451 
3452 # Generate vectors.S, the trap/interrupt entry points.
3453 # There has to be one entry point per interrupt number
3454 # since otherwise there's no way for trap() to discover
3455 # the interrupt number.
3456 
3457 print "# generated by vectors.pl - do not edit\n";
3458 print "# handlers\n";
3459 print ".globl alltraps\n";
3460 for(my $i = 0; $i < 256; $i++){
3461     print ".globl vector$i\n";
3462     print "vector$i:\n";
3463     if(!($i == 8 || ($i >= 10 && $i <= 14) || $i == 17)){
3464         print "  pushl \$0\n";
3465     }
3466     print "  pushl \$$i\n";
3467     print "  jmp alltraps\n";
3468 }
3469 
3470 print "\n# vector table\n";
3471 print ".data\n";
3472 print ".globl vectors\n";
3473 print "vectors:\n";
3474 for(my $i = 0; $i < 256; $i++){
3475     print "  .long vector$i\n";
3476 }
3477 
3478 # sample output:
3479 #   # handlers
3480 #   .globl alltraps
3481 #   .globl vector0
3482 #   vector0:
3483 #     pushl $0
3484 #     pushl $0
3485 #     jmp alltraps
3486 #   ...
3487 #
3488 #   # vector table
3489 #   .data
3490 #   .globl vectors
3491 #   vectors:
3492 #     .long vector0
3493 #     .long vector1
3494 #     .long vector2
3495 #   ...
3496 
3497 
3498 
3499 
