3550 #!/usr/bin/perl -w
3551 
3552 # Generate vectors.S, the trap/interrupt entry points.
3553 # There has to be one entry point per interrupt number
3554 # since otherwise there's no way for trap() to discover
3555 # the interrupt number.
3556 
3557 print "# generated by vectors.pl - do not edit\n";
3558 print "# handlers\n";
3559 print ".globl alltraps\n";
3560 for(my $i = 0; $i < 256; $i++){
3561     print ".globl vector$i\n";
3562     print "vector$i:\n";
3563     if(!($i == 8 || ($i >= 10 && $i <= 14) || $i == 17)){
3564         print "  pushl \$0\n";
3565     }
3566     print "  pushl \$$i\n";
3567     print "  jmp alltraps\n";
3568 }
3569 
3570 print "\n# vector table\n";
3571 print ".data\n";
3572 print ".globl vectors\n";
3573 print "vectors:\n";
3574 for(my $i = 0; $i < 256; $i++){
3575     print "  .long vector$i\n";
3576 }
3577 
3578 # sample output:
3579 #   # handlers
3580 #   .globl alltraps
3581 #   .globl vector0
3582 #   vector0:
3583 #     pushl $0
3584 #     pushl $0
3585 #     jmp alltraps
3586 #   ...
3587 #
3588 #   # vector table
3589 #   .data
3590 #   .globl vectors
3591 #   vectors:
3592 #     .long vector0
3593 #     .long vector1
3594 #     .long vector2
3595 #   ...
3596 
3597 
3598 
3599 
